services:
  server:
    build:
      context: ..
      dockerfile: deploy/server/Dockerfile
      args:
        GIT_REF: ${GIT_REF:-main}
        GIT_REPO_URL: "https://github.com/lsqlebai/slam.git"
    container_name: slam_server
    volumes:
      - slam_sport_db:/data
      - ./config/app.container.yml:/app/config/app.yml:ro
    environment:
      - AI_API_KEY=${AI_API_KEY}
    ports:
      - "3000:3000"
  web:
    build:
      context: ..
      dockerfile: deploy/web/Dockerfile
      args:
        GITHUB_REPO: "lsqlebai/slam"
    container_name: slam_web
    depends_on:
      - server
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
volumes:
  slam_sport_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db
